version: "3.6"
services:
  iris:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 51773:51773
      - 52773:52773
    volumes:
      - ~/iris.key:/usr/irissys/mgr/iris.key
      - ./:/irisdev/app
  web:
    build:
      context: .
      dockerfile: SampleWebApp/Dockerfile
    restart: always
    ports:
      - 5001:80
